name: VERITAS_CorePlugin
version: ${project.version}
main: jp.dip.monsterlifeserver.varitas_coreplugin.VARITAS_CorePlugin
api-version: 1.13

commands:
  gexp:
    description: gexp
  test:
    description: test